#Exercício Python 9: Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.
num = int(input('Digite um número para ver sua tabuada: '))
print("-" * 20)
print(f'{num:2} X 0  = {(num * 0)}')
print(f'{num:2} X 1  = {(num * 1)}')
print(f'{num:2} X 2  = {(num * 2)}')
print(f'{num:2} X 3  = {(num * 3)}')
print(f'{num:2} X 4  = {(num * 4)}')
print(f'{num:2} X 5  = {(num * 5)}')
print(f'{num:2} X 6  = {(num * 6)}')
print(f'{num:2} X 7  = {(num * 7)}')
print(f'{num:2} X 8  = {(num * 8)}')
print(f'{num:2} X 9  = {(num * 9)}')
print(f'{num:2} X 10 = {(num * 10)}')
print('-' * 20)