n = int(input('Insira um número: '))
print('-' * 15)
print(' 1 x', n, '= {}'.format(n * 1))
print(' 2 x', n,'= {}'.format(n * 2))
print(' 3 x', n,'= {}'.format(n * 3))
print(' 4 x', n, '= {}'.format(n * 4))
print(' 5 x', n,'= {}'.format(n * 5))
print(' 6 x', n,'= {}'.format(n * 6))
print(' 7 x', n, '= {}'.format(n * 7))
print(' 8 x', n,'= {}'.format(n * 8))
print(' 9 x', n,'= {}'.format(n * 9))
print('10 x', n, '= {}'.format(n * 10))
print('-' * 15)
